/**
 * Website Leads — Google Apps Script Web App
 *
 * Receives a lead JSON payload from the Next.js app (src/lib/marketing/
 * google-sheets.ts) and appends it as a new row to the "Website Leads"
 * sheet. Deploy this bound to your Google Sheet — see
 * docs/GOOGLE_SHEETS_SETUP.md for the exact steps.
 *
 * This script generates NOTHING itself except the Date/Time columns — the
 * Lead ID is generated by the Next.js app (so the same ID appears in the
 * app's own local record and in this sheet) and simply appended as-is.
 */

const SHEET_NAME = "Website Leads";

// One row per column, in the exact order they're written — keep this in
// sync with the header row you create in the sheet (see the setup doc).
const COLUMNS = [
  "Lead ID",
  "Date",
  "Time",
  "Name",
  "Email",
  "Phone",
  "Company",
  "Website",
  "Industry",
  "Services Required / Business Goal",
  "Marketing Budget",
  "Message / Challenge",
  "Lead Source",
  "Landing Page",
  "Case Study Viewed",
  "Industry Viewed",
  "UTM Source",
  "UTM Medium",
  "UTM Campaign",
  "UTM Term",
  "UTM Content",
  "Device",
  "Status",
  "Priority",
  "Notes",
];

function doPost(e) {
  try {
    const body = JSON.parse(e.postData.contents);

    const expectedSecret = PropertiesService.getScriptProperties().getProperty("SHARED_SECRET");
    if (expectedSecret && body.secret !== expectedSecret) {
      return jsonResponse({ ok: false, error: "unauthorized" }, 401);
    }

    const lead = body.lead || {};
    if (!lead.leadId || !lead.name || !lead.email) {
      return jsonResponse({ ok: false, error: "missing_required_fields" }, 400);
    }

    const sheet = getOrCreateSheet();
    const now = new Date();

    sheet.appendRow([
      lead.leadId,
      Utilities.formatDate(now, Session.getScriptTimeZone(), "dd-MMM-yyyy"),
      Utilities.formatDate(now, Session.getScriptTimeZone(), "HH:mm"),
      lead.name || "",
      lead.email || "",
      lead.phone || "",
      lead.company || "",
      lead.website || "",
      lead.industry || "",
      lead.businessGoal || "",
      lead.budget || "",
      lead.message || "",
      lead.leadSource || "Website",
      lead.landingPage || "",
      lead.caseStudyViewed || "",
      lead.industryViewed || "",
      lead.utmSource || "",
      lead.utmMedium || "",
      lead.utmCampaign || "",
      lead.utmTerm || "",
      lead.utmContent || "",
      lead.device || "",
      "New",
      "Warm",
      "",
    ]);

    return jsonResponse({ ok: true, leadId: lead.leadId });
  } catch (err) {
    return jsonResponse({ ok: false, error: String(err) }, 500);
  }
}

function getOrCreateSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) {
    sheet = ss.insertSheet(SHEET_NAME);
  }
  if (sheet.getLastRow() === 0) {
    sheet.appendRow(COLUMNS);
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function jsonResponse(obj, statusCode) {
  // Apps Script Web Apps can't set an HTTP status code on the response —
  // statusCode is accepted here only so callers reading this file can see
  // the intended status; the body's `ok`/`error` fields are what the Next.js
  // side actually checks (see forwardLeadToGoogleSheets).
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

/**
 * Run this once manually from the Apps Script editor (select `setup` in the
 * function dropdown, click Run) to create the sheet + header row ahead of
 * the first real submission, and to grant the script the permissions it
 * needs. Safe to re-run — getOrCreateSheet() is idempotent.
 */
function setup() {
  getOrCreateSheet();
}
